### ISSUE TITLE
new additional resources for sub link

### ISSUE THREAD

**Issue by Graveyard9988** [ALIILAPRO/v2rayNG-Config#1]
https://github.com/soroushmirzaei/telegram-configs-collector/blob/main/subscription%20links.json
https://github.com/Leon406/jsdelivr/blob/master/subscribe/subpool2
https://github.com/yyyr-otz/tele-providers-collector/blob/master/script/source/subscription%20links-all.json

**Comment by ALIILAPRO** [comment]
> https://github.com/soroushmirzaei/telegram-configs-collector/blob/main/subscription%20links.json https://github.com/Leon406/jsdelivr/blob/master/subscribe/subpool2 https://github.com/yyyr-otz/tele-providers-collector/blob/master/script/source/subscription%20links-all.json

I'll checked.
