### ISSUE TITLE
درخواست مجوز استفاده برای عموم

### ISSUE THREAD

**Issue by barry-far** [ALIILAPRO/v2rayNG-Config#2]
سلام وقتت بخیر و ممنون بابت کانفیگ های رایگانی که برای مردم قرار میدی.
ازت میخواستم اجازه بگیرم که لینک سابسکریپشنت رو به رپوزیتوری مخزن خودم اضافه کنم تا مردم بیشتری بتونن از این کانفیگ ها بهره مند بشن...

لینک پروژه بنده : https://github.com/barry-far/V2ray-Configs

**Comment by ALIILAPRO** [comment]
> سلام وقتت بخیر و ممنون بابت کانفیگ های رایگانی که برای مردم قرار میدی. ازت میخواستم اجازه بگیرم که لینک سابسکریپشنت رو به رپوزیتوری مخزن خودم اضافه کنم تا مردم بیشتری بتونن از این کانفیگ ها بهره مند بشن...
> 
> لینک پروژه بنده : https://github.com/barry-far/V2ray-Configs


سلام داداش. جدا از اینکه به فکر مردم هستی خیلی ممنون که این احترام رو برای استفاده از لینک به من گذاشتی. راحت باش میتونی به مخزن اضافه کنی.

**Comment by barry-far** [comment]
انجام وظیفه س. 🫂
